### ISSUE TITLE
Can you remove affiliate links cloacking?

### ISSUE THREAD

**Issue by Geineh** [newhouse/url-tracking-stripper#101]
Hi

WordPress has addon for referal links. Result of its work is hidden affiliate links

I found service which can decrypt / decode URLs
https://prozavr.ru/tools/rasshifrovka-korotkih-ssilok.php

So, if we will put link https://www.kobzarev.com/r/smmbox in service above we will get next:
https://www.kobzarev.com/r/smmbox/	https://smmbox.com/c/349271	https://smmbox.com/?utm_source=partner&utm_campaign=partner&utm_medium=partner

But page is only https://smmbox.com/

Can u add this funclionality 2 exclude this stupid refferal links?

### What is your browser?

- [ ] Chrome

### What is your operating system?

- [ ] Windows

### Description (please include examples/screenshots where applicable)

![image](https://user-images.githubusercontent.com/36577960/83088809-70bd8680-a09d-11ea-9fde-3e4d34c9e0e5.png)

**Comment by newhouse** [comment]
Hi there @Geineh and thanks for the report.

I've taken a look, and this is not something that the extension can do. If the target URL were something that I could extract from the original URL, then I could skip the 1 intermediate step. 

This case here requires the URLs to be followed in order to see where it goes, and the extension does not support these scenarios at this time. I'll keep this in mind for the future, however!

Thanks!

**Comment by Geineh** [comment]
Thx for answer & hope you will add it in future.

Have a nice day!
