### ISSUE TITLE
Rewrite urls when copied clipboard

### ISSUE THREAD

**Issue by menzow** [newhouse/url-tracking-stripper#28]
Sites like facebook and google won't let you copy external urls. Instead they put a verbose tracking url in your clipboard. Normally I go through the hassle of opening the tracking url and copying the destination from my address bar before sharing it.

To simplify this process I extended your plugin to listen for any copy events and rewrite urls in the clipboard data. If this isn't considered out of scope I could create a PR for it.

**Comment by newhouse** [comment]
I definitely like this idea, but I'm worried how it will be implemented. I see you've begun some work on it so I'll have a look at that, and probably also take a stab at it myself and see what we can come up with.

**Comment by newhouse** [comment]
So working backwards from the user experience, I'd see the following ways a User would perform this:
a) Right-click and use the pre-existing "Copy Link Address" context menu item.
b) Right-click and use a custom context menu item for this extension, labeled something like "Copy Clean Link Address".
c) Right-click and use the pre-existing "Copy" context menu item.

In my experimentation, here are my findings on each:
a) This would be the most ideal hook, but it does not seem like there is an event that can be listened to for this. I'll keep looking, but this is probably a no-go as the `copy`/`oncopy` does not fire when this action is performed.
b) This would be the 2nd-most desirable way. Probably not that tough to implement.
c) Similar to `b`, but probably less desirable since the original copy functionality is completely gone in case you wanted to get it unaltered. Also, may as well do `b` if you're going to do this to highlight what you're doing and remind users how super cool the extension is for them.

What do you think?

**Comment by newhouse** [comment]
OK, @menzow  so a few things:

I've noticed that on Gmail and Google Search organic results, the "Copy Link Address" command does not copy the junky, redirect link that it would pass you through if you were to actually click on it. This is good for all users. Of course, this does not alter the behavior of Facebook redirecting, and others.

Through my experimentation, it seems like there's not a way to tap into Chrome's "Copy Link Address" command, and tapping into the "Copy" command is kinda lame and dirty and not really focused.

I think it's best to utilize the `contextMenus` API wiht the `link` context filter. I've created a branch here that has my implementation of a Context Menu that will both skip redirects and remove tracking paramters:
https://github.com/newhouse/url-tracking-stripper/pull/30

Have a look please and let me know what you think...

**Comment by newhouse** [comment]
Closed via https://github.com/newhouse/url-tracking-stripper/pull/33

**Comment by menzow** [comment]
Hey @newhouse ,

Had a busy week and I completely missed your feedback on this one! I agree that with the available options, adding a contextMenu item is the only way to achieve consistent behavior. My implementation relied on setting a listener on contextmenu and hope that it didn't conflict with the listener on the target site.

Chrome is working on a [clipboard api](https://developer.chrome.com/apps/clipboard). With this api you can simply register a event listener like: [`chrome.clipboard.onClipboardDataChanged.addListener`](https://developer.chrome.com/apps/clipboard#event-onClipboardDataChanged). And replace tracking urls in any text copied by the user. The API is currently still in the dev channel but it's something to keep in mind.

**Comment by newhouse** [comment]
That clipboard API looks interesting...hopefully I'll notice when it comes out, thanks!
