### ISSUE TITLE
[Feature request] spm parameter

### ISSUE THREAD

**Issue by JokerQyou** [newhouse/url-tracking-stripper#38]
The `spm` parameter is used on websites operated by Alibaba and its related companies. Here are some documentation (in Chinese):

- https://www.zhihu.com/question/62813754
- http://bigdata.taobao.com/docs/doc.htm?treeId=1&articleId=101782&docType=1 (this doc might be outdated)

 I'll summary some in English:

- `spm` stands for `super position model`, it's basically the same as the `utm_` parameters used by Google Analytics.
- For example the URL `https://cn.aliyun.com/about?spm=5176.8142029.631162.about.702b614aLj4URY`, it contains the `spm` parameter, and its value is `5176.8142029.631162.about.702b614aLj4URY`.
  - `spm` parameter is formatted like this: `spm=spmA.spmB.spmC.spmD.spmE`
  - `spmA` identifies a website;
  - `spmB` identifies a page on that website;
  - `spmC` identifies a block on that page;
  - `spmD` further identifies a specific position in that block;
  - `spmE` is a random string generated with current time, which could distinguish visits of the same link from each other by time;

You could visit website of Aliyun or Aliexpress to see the `spm` parameter in action. I really like this extension for its simplicity and effectiveness to block `utm` and other tracking parameters, and I hope you could consider adding `spm` to that list too.

I forked this repository and found the right file to modify, but unfortunately I have not yet figured out how to build it. Maybe you could add some instructions about building the extension to README, if you have time?

Thank you again for this amazing extension.

**Comment by JokerQyou** [comment]
Forgot to mention a detail: for some websites (e.g., Aliyun), the `href` of links on the webpage is normal (without `spm` parameter), they use Javascript to generate and add the parameter on the fly, at the time you click (or right click) a link.

**Comment by newhouse** [comment]
Hey @JokerQyou thanks for the kind words and the great info you provided for this tracker!

I've gone ahead and added support for the `spm` tracker via https://github.com/newhouse/url-tracking-stripper/pull/39 and will be available shortly in version `4.1.1`. I think this should solve even the on-the-fly Javascript-generated parameters because the extension works via the [webNavigation](https://developer.chrome.com/extensions/webNavigation) and [webRequest]() APIs, as opposed to monitoring for click events on elements (with the exception of the right-click `Copy and Clean Link`, where these Javascript changes should not matter). Please let me know if you find anything weird.

I've also updated the `README` to help developers figure out how to get it running so they can contribute!
