### ISSUE TITLE
Add feedproxy.google.com (Feedburner) redirect support

### ISSUE THREAD

**Issue by archon810** [newhouse/url-tracking-stripper#55]
For example: http://feedproxy.google.com/~r/AndroidPolice/~3/Se1olsLxDHE/.

**Comment by newhouse** [comment]
Hi @archon810 and thanks for using the extension and for this ticket.

The way that the extension works today is to work with redirects where the "target" URL is present in the original URL (usually in some query parameter of the original URL). It is not designed to need to actually *follow* links on the page in order to figure out where they go. That would result in many calls being made from a User's browser without their knowledge and likely without their intention of ever going to any of those URLs. This would not only increase the network and CPU usage of the User's computer, but also likely end up unintentionally getting them tracked even more.

Unfortunately I don't see a way to extract the "target" URL from the example you've provided here. If you can show me how that can be done, I'd be happy to re-open and investigate this!

**Comment by archon810** [comment]
@newhouse Well, the goal and scope of this feature was meant to be for when you manually copy the link - if redirects are resolved only at that time, it'll be not worse than simply following that url and copying the link after.

**Comment by newhouse** [comment]
Ah, gotcha! That could be done, but not very high priority as it's definitely in the "secondary" functionality of the extension.  I've created a new ticket linked to this for that idea though so I don't forget about it!
